import { Degree, Module, Lesson, Question, AppSetting, UserProfile, DeliveredInstruction, SupportMaterial } from '../types';

export const INITIAL_SETTINGS: AppSetting = {
  id: 'global_config',
  institutionName: 'Faculdade Maçônica Universal de Estudos Tradicionais',
  defaultPassingGrade: 70,
  allowPreviousDegreesGlobal: true,
  maxUploadSizeBytes: 15 * 1024 * 1024, // 15MB
  requireApprovalForRegistration: true,
  grandMasterName: "S.'.G.'.M.'. DARLAN MARTINS",
  grandMasterRole: 'Soberano Grão-Mestre',
  updatedAt: new Date().toISOString(),
};

export const INITIAL_DEGREES: Degree[] = [
  {
    id: 'grau_1',
    degreeNumber: 1,
    title: 'Grau 01',
    name: 'Aprendiz Maçom',
    description: 'O início da jornada iniciática. O trabalho primordial de desbastar a Pedra Bruta, o desenvolvimento do silêncio, da moral e dos primeiros passos no Templo Interior.',
    color: '#3b82f6',
    allowPreviousDegrees: true,
    isActive: true,
    order: 1,
    totalLessons: 3,
    completedLessons: 0,
    progressPercent: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'grau_2',
    degreeNumber: 2,
    title: 'Grau 02',
    name: 'Companheiro Maçom',
    description: 'O aprofundamento filosófico, as viagens simbólicas, as Sete Artes e Ciências Liberais, a passagem da Pedra Bruta para a Pedra Cúbica e a atuação fraterna no mundo.',
    color: '#10b981',
    allowPreviousDegrees: true,
    isActive: true,
    order: 2,
    totalLessons: 3,
    completedLessons: 0,
    progressPercent: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'grau_3',
    degreeNumber: 3,
    title: 'Grau 03',
    name: 'Mestre Maçom',
    description: 'A plenitude dos direitos e deveres maçônicos. A reflexão profunda sobre a transmutação, a Lenda Tradicional, a Câmara do Meio e a perseverança no dever.',
    color: '#d4af37',
    allowPreviousDegrees: true,
    isActive: true,
    order: 3,
    totalLessons: 3,
    completedLessons: 0,
    progressPercent: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_MODULES: Module[] = [
  {
    id: 'mod_1_1',
    degreeId: 'grau_1',
    degreeNumber: 1,
    title: 'Módulo 1.1: Princípios Gerais e a Pedra Bruta',
    description: 'Introdução aos fundamentos éticos, simbólicos e históricos do Grau de Aprendiz.',
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mod_1_2',
    degreeId: 'grau_1',
    degreeNumber: 1,
    title: 'Módulo 1.2: A Estrutura do Templo e as Três Luzes',
    description: 'Estudo da geometria sagrada do Templo, suas colunas e os instrumentos de trabalho.',
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mod_2_1',
    degreeId: 'grau_2',
    degreeNumber: 2,
    title: 'Módulo 2.1: As Viagens e as Ciências Liberais',
    description: 'As cinco viagens do Companheiro e o estudo do Trivium e Quadrivium.',
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mod_2_2',
    degreeId: 'grau_2',
    degreeNumber: 2,
    title: 'Módulo 2.2: A Pedra Cúbica e a Geometria Operativa',
    description: 'A transformação da matéria pelo conhecimento e a elevação da consciência social.',
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mod_3_1',
    degreeId: 'grau_3',
    degreeNumber: 3,
    title: 'Módulo 3.1: A Câmara do Meio e a Tradição',
    description: 'A solenidade do Grau 3, o luto iniciático e a reconstrução perene.',
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mod_3_2',
    degreeId: 'grau_3',
    degreeNumber: 3,
    title: 'Módulo 3.2: O Ramo de Acácia e a Consciência',
    description: 'A imortalidade moral do trabalho virtuoso e a liderança fraterna no mundo.',
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_LESSONS: Lesson[] = [
  // --- GRAU 1: APRENDIZ ---
  {
    id: 'inst_1_1',
    number: 1,
    title: 'Instrução 01: O Desbaste da Pedra Bruta e o Autoaperfeiçoamento',
    subtitle: 'Compreensão do Maço, Cinzel e a disciplina moral do Neófito',
    degreeId: 'grau_1',
    degreeNumber: 1,
    moduleId: 'mod_1_1',
    moduleTitle: 'Módulo 1.1: Princípios Gerais e a Pedra Bruta',
    objective: 'Compreender a alegoria da Pedra Bruta como símbolo do homem no estado natural de ignorância e imperfeições, e assimilar os instrumentos de transformação pessoal e moral.',
    content: `
### 1. A Natureza da Pedra Bruta
Na Tradição Simbólica, a **Pedra Bruta** representa a mente e o caráter do homem ao ingressar na Instituição. Ela é informe, áspera e repleta de arestas. Essas arestas simbolizam as paixões desordenadas, os preconceitos, o orgulho egoísta e a ignorância.

> *"Não viemos para transformar o mundo exterior antes de realizarmos a profunda obra de lapidação em nosso próprio templo interior."*

### 2. Os Instrumentos de Trabalho do Aprendiz
Para realizar essa obra, o Aprendiz recebe dois instrumentos fundamentais:
* **O Maço (ou Malhete):** Representa a **Força de Vontade**, a energia direcionada e a determinação incansável necessária para agir sobre si mesmo.
* **O Cinzel:** Representa a **Razão e o Discernimento**, que direciona a força bruta para onde ela é verdadeiramente necessária, evitando a destruição da matéria preciosa.

### 3. A Aplicação Prática no Dia a Dia
O trabalho de desbastar a pedra não ocorre apenas dentro de quatro paredes sagradas. Ele se manifesta:
1. No controle das palavras e na prática do silêncio virtuoso.
2. Na capacidade de ouvir antes de julgar.
3. Na honestidade irrepreensível em todas as transações comerciais e profissionais.
4. Na dedicação constante ao estudo, à família e à sociedade.
    `.trim(),
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    audioUrl: '',
    attachments: [
      { name: 'Guia_Estudo_Pedra_Bruta.pdf', url: '#', type: 'application/pdf', size: '1.4 MB' },
      { name: 'Simbologia_Maco_Cinzel.docx', url: '#', type: 'application/docx', size: '540 KB' },
    ],
    essayPrompt: 'Elabore uma Prancha de Trabalho (1 a 3 páginas) dissertando sobre: "Como o manuseio harmônico do Maço e do Cinzel pode ser aplicado para superar um desafio moral contemporâneo na vida profana e maçônica."',
    minimumPassingGrade: 70,
    status: 'published',
    author: 'Ir. Grande Orador da Academia',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'inst_1_2',
    number: 2,
    title: 'Instrução 02: A Estrutura do Templo e as Três Grandes Colunas',
    subtitle: 'Sabedoria, Força e Beleza como pilares de sustentação da Ordem',
    degreeId: 'grau_1',
    degreeNumber: 1,
    moduleId: 'mod_1_2',
    moduleTitle: 'Módulo 1.2: A Estrutura do Templo e as Três Luzes',
    objective: 'Analisar a orientação cósmica do Templo Maçônico e o papel filosófico das colunas da Sabedoria, Força e Beleza.',
    content: `
### 1. A Orientação do Templo
O Templo está orientado do Ocidente para o Oriente, em extensão de Norte a Sul e em profundidade da Terra ao Céu. Essa amplitude simboliza a universalidade da fraternidade humana e a busca incessante pela Verdade e pela Luz.

### 2. As Três Colunas Principais
O Templo é idealmente sustentado por três colunas emblemáticas:
* **Sabedoria (Minerva/Salomão):** Para conceber, arquitetar e projetar obras nobres e justas.
* **Força (Hércules/Hiram de Tiro):** Para sustentar, executar e manter com vigor as resoluções éticas diante das tempestades.
* **Beleza (Vênus/Hiram Abiff):** Para adornar, harmonizar e conceder elegância moral às atitudes humanas.

> *"A Sabedoria cria o plano, a Força edifica o alicerce, e a Beleza harmoniza a convivência fraterna."*
    `.trim(),
    videoUrl: '',
    audioUrl: '',
    attachments: [
      { name: 'Diagrama_Estrutura_Templo.pdf', url: '#', type: 'application/pdf', size: '2.1 MB' },
    ],
    essayPrompt: 'Apresente uma Prancha de Trabalho correlacionando as três colunas (Sabedoria, Força e Beleza) com as tomadas de decisões éticas na governança institucional e comunitária.',
    minimumPassingGrade: 70,
    status: 'published',
    author: 'Ir. Primeiro Vigilante Docente',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'inst_1_3',
    number: 3,
    title: 'Instrução 03: O Silêncio, a Disciplina e o Compromisso Fraterno',
    subtitle: 'A prática reflexiva da Coluna do Norte e a guarda dos sentidos',
    degreeId: 'grau_1',
    degreeNumber: 1,
    moduleId: 'mod_1_1',
    moduleTitle: 'Módulo 1.1: Princípios Gerais e a Pedra Bruta',
    objective: 'Compreender a virtude iniciática do silêncio como ferramenta de introspecção e controle das reações impensadas.',
    content: `
### 1. O Silêncio Iniciático
Ao Aprendiz cumpre ouvir, observar e meditar. O silêncio não é imposição de submissão, mas sim o mais refinado exercício pedagógico da Antiguidade clássica, inspirado nas escolas pitagóricas.

### 2. A Proteção contra o Ruído Exterior
No mundo moderno hiperconectado, o homem é bombardeado por estímulos ininterruptos. A prática do silêncio maçônico educa a mente a:
1. Filtrar opiniões superficiais.
2. Não reagir com cólera a provocações.
3. Cultivar a escuta empática para com os irmãos e semelhantes.

> *"Quem não aprende a calar quando é mister, jamais saberá falar quando for oportuno."*
    `.trim(),
    videoUrl: '',
    audioUrl: '',
    attachments: [],
    essayPrompt: 'Elabore sua Prancha de Trabalho abordando: "O Silêncio como Escudo Ético e Ferramenta de Discernimento na Era da Informação."',
    minimumPassingGrade: 70,
    status: 'published',
    author: 'Ir. Segundo Vigilante',
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-01-20T10:00:00Z',
  },

  // --- GRAU 2: COMPANHEIRO ---
  {
    id: 'inst_2_1',
    number: 1,
    title: 'Instrução 01: A Estrela Flamígera e a Letra G',
    subtitle: 'O homem regenerado pelo conhecimento e a luz do intelecto',
    degreeId: 'grau_2',
    degreeNumber: 2,
    moduleId: 'mod_2_1',
    moduleTitle: 'Módulo 2.1: As Viagens e as Ciências Liberais',
    objective: 'Desvelar os mistérios da Estrela de Cinco Pontas, o Pentagrama moral e o simbolismo da Geometria sagrada.',
    content: `
### 1. A Estrela Pentagonal
A Estrela Flamígera ilumina os trabalhos do Companheiro. Seus cinco vértices evocam os cinco sentidos purificados, as cinco faculdades da inteligência e a harmonia do corpo humano idealizado de Vitrúvio.

### 2. A Misteriosa Letra G
A letra no centro da Estrela aponta para múltiplas dimensões do saber:
* **Geometria:** A ciência fundamental dos construtores.
* **Geração:** O princípio vital e criador universal.
* **Gravitação:** A atração harmônica que une os corpos e os corações fraternos.
* **Gênio:** A chama da criatividade intelectual e artística.
* **Gnose:** O conhecimento direto e transcendental da verdade.
    `.trim(),
    videoUrl: '',
    audioUrl: '',
    attachments: [
      { name: 'Estudo_Estrela_Flamigera.pdf', url: '#', type: 'application/pdf', size: '1.8 MB' },
    ],
    essayPrompt: 'Escreva uma Prancha de Trabalho discursando sobre como a Geometria Sagrada e os cinco sentidos podem orientar o Companheiro na construção de pontes fraternas na sociedade.',
    minimumPassingGrade: 70,
    status: 'published',
    author: 'Ir. Mestre de Instrução do Grau 2',
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'inst_2_2',
    number: 2,
    title: 'Instrução 02: As Sete Artes e Ciências Liberais',
    subtitle: 'O Trivium (Gramática, Lógica, Retórica) e o Quadrivium (Aritmética, Geometria, Música, Astronomia)',
    degreeId: 'grau_2',
    degreeNumber: 2,
    moduleId: 'mod_2_1',
    moduleTitle: 'Módulo 2.1: As Viagens e as Ciências Liberais',
    objective: 'Analisar o currículo clássico de emancipação humana e seu valor inestimável para a formação do livre-pensador.',
    content: `
### 1. A Importância do Conhecimento
O Companheiro não apenas desbasta a pedra, mas estuda como encaixá-la no grande edifício da civilização.

### 2. O Trivium (A Palavra e a Razão)
* **Gramática:** O domínio preciso da linguagem e da expressão.
* **Lógica (Dialética):** A arte de pensar com coerência e identificar falácias.
* **Retórica:** A eloquência a serviço da verdade e da persuasão virtuosa.

### 3. O Quadrivium (A Mensuração do Universo)
* **Aritmética:** O número em si mesmo e as proporções.
* **Geometria:** O número no espaço e as formas.
* **Música:** O número no tempo e as harmonias sonoras.
* **Astronomia:** O número no espaço e no tempo, o movimento dos astros.
    `.trim(),
    videoUrl: '',
    audioUrl: '',
    attachments: [],
    essayPrompt: 'Apresente uma Prancha de Trabalho articulando a importância do Trivium e Quadrivium para a defesa da verdade e combate à desinformação no século XXI.',
    minimumPassingGrade: 70,
    status: 'published',
    author: 'Ir. Orador Adjunto',
    createdAt: '2026-02-05T10:00:00Z',
    updatedAt: '2026-02-05T10:00:00Z',
  },
  {
    id: 'inst_2_3',
    number: 3,
    title: 'Instrução 03: A Alavanca, o Nível e o Prumo na Ação Social',
    subtitle: 'Instrumentos de elevação moral, igualdade e retidão de conduta',
    degreeId: 'grau_2',
    degreeNumber: 2,
    moduleId: 'mod_2_2',
    moduleTitle: 'Módulo 2.2: A Pedra Cúbica e a Geometria Operativa',
    objective: 'Integrar a ferramenta da Alavanca, da Régua de 24 polegadas, do Nível e do Prumo nas relações de solidariedade comunitária.',
    content: `
### 1. O Nível e o Prumo
O Nível nos ensina que todos os homens provêm da mesma origem terrena e partilham a mesma dignidade essencial. O Prumo nos lembra da integridade vertical e da justiça inabalável.

### 2. A Alavanca
Multiplica a força individual em benefício da coletividade. Aliada ao ponto de apoio da Fraternidade, a Alavanca é capaz de erguer os fardos mais pesados da dor humana.
    `.trim(),
    videoUrl: '',
    audioUrl: '',
    attachments: [],
    essayPrompt: 'Elabore sua Prancha de Trabalho demonstrando como a Alavanca Maçônica da solidariedade pode ser operacionalizada em iniciativas sociais da sua Loja.',
    minimumPassingGrade: 70,
    status: 'published',
    author: 'Ir. Primeiro Vigilante',
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-10T10:00:00Z',
  },

  // --- GRAU 3: MESTRE ---
  {
    id: 'inst_3_1',
    number: 1,
    title: 'Instrução 01: A Lenda do Mestre Hiram Abiff e a Morte Filosófica',
    subtitle: 'A fidelidade incondicional ao dever e a transmutação do ser',
    degreeId: 'grau_3',
    degreeNumber: 3,
    moduleId: 'mod_3_1',
    moduleTitle: 'Módulo 3.1: A Câmara do Meio e a Tradição',
    objective: 'Compreender a profundidade dramática e moral da lenda tradicional, onde a integridade moral triunfa sobre a violência dos vícios humanos.',
    content: `
### 1. A Sublime Alegoria do Terceiro Grau
A elevação ao Grau de Mestre convida o irmão a vivenciar o ápice do simbolismo iniciático: a firmeza inquebrantável diante das três grandes sombras que ameaçam a humanidade:
* **A Ignorância:** Que julga sem conhecimento.
* **O Fanatismo:** Que persegue com cegueira.
* **A Ambição desmedida:** Que trai os princípios por ganhos efêmeros.

> *"O verdadeiro Mestre não teme a dissolução do que é perecível, pois sua fidelidade aos princípios é eterna."*
    `.trim(),
    videoUrl: '',
    audioUrl: '',
    attachments: [
      { name: 'Ensaio_Lenda_Hiram_Tradicao.pdf', url: '#', type: 'application/pdf', size: '2.5 MB' },
    ],
    essayPrompt: 'Escreva uma Prancha de Trabalho analisando os três algozes de Hiram (Ignorância, Fanatismo e Ambição) e como o Mestre Maçom atua como baluarte contra essas forças na sociedade.',
    minimumPassingGrade: 70,
    status: 'published',
    author: 'Venerável Mestre Regente',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'inst_3_2',
    number: 2,
    title: 'Instrução 02: O Ramo de Acácia e a Esperança na Imortalidade Moral',
    subtitle: 'O renascimento espiritual e a perenidade das boas obras',
    degreeId: 'grau_3',
    degreeNumber: 3,
    moduleId: 'mod_3_2',
    moduleTitle: 'Módulo 3.2: O Ramo de Acácia e a Consciência',
    objective: 'Explorar o vegetal incorruptível da Acácia como símbolo da alma pura e da continuidade da causa da humanidade.',
    content: `
### 1. A Acácia: O Vegetal Sagrado
A Acácia, árvore de madeira incorruptível e folhas verdes perenes, sinaliza aos buscadores que a virtude não pode ser sepultada no esquecimento.

### 2. A Imortalidade das Obras
Aquilo que fazemos apenas para nós mesmos perece conosco; mas aquilo que edificamos em prol de nossos semelhantes e da posteridade torna-se imortal.
    `.trim(),
    videoUrl: '',
    audioUrl: '',
    attachments: [],
    essayPrompt: 'Produza sua Prancha de Trabalho dissertando sobre o significado da frase: "A Acácia me é conhecida", explorando sua aplicação no legado ético que o irmão deixará à posteridade.',
    minimumPassingGrade: 70,
    status: 'published',
    author: 'Ir. Grande Chanceler',
    createdAt: '2026-03-05T10:00:00Z',
    updatedAt: '2026-03-05T10:00:00Z',
  },
  {
    id: 'inst_3_3',
    number: 3,
    title: 'Instrução 03: A Câmara do Meio e a Mestria da Vida',
    subtitle: 'O governo de si mesmo e a liderança generosa na Fraternidade',
    degreeId: 'grau_3',
    degreeNumber: 3,
    moduleId: 'mod_3_1',
    moduleTitle: 'Módulo 3.1: A Câmara do Meio e a Tradição',
    objective: 'Identificar as responsabilidades do Mestre em transmitir o fogo sagrado do conhecimento às novas gerações de Aprendizes e Companheiros.',
    content: `
### 1. A Câmara do Meio
O Mestre atinge o centro interior, onde reina a calma serena da razão e a luz sem sombras. Ele é chamado a ser exemplo vivo de tolerância, concórdia e justiça.

### 2. A Liderança pelo Exemplo
O título de Mestre não confere privilégios vaidosos, mas sim uma carga multiplicada de responsabilidades perante os mais novos na caminhada iniciática.
    `.trim(),
    videoUrl: '',
    audioUrl: '',
    attachments: [],
    essayPrompt: 'Elabore sua Prancha de Trabalho sintetizando os deveres pedagógicos e fraternais do Mestre Maçom no acolhimento e mentoria dos irmãos Aprendizes e Companheiros.',
    minimumPassingGrade: 70,
    status: 'published',
    author: 'Ir. Ilustre Inspetor Litúrgico',
    createdAt: '2026-03-10T10:00:00Z',
    updatedAt: '2026-03-10T10:00:00Z',
  },
];

// Helper to generate exactly 10 questions per lesson (90 questions total)
export const INITIAL_QUESTIONS: Question[] = [
  // --- QUESTIONS FOR INSTRUCTION 1.1 (Pedra Bruta) ---
  {
    id: 'q_1_1_1',
    lessonId: 'inst_1_1',
    degreeNumber: 1,
    order: 1,
    type: 'multiple_choice',
    prompt: 'No simbolismo maçônico do Grau 1, o que a "Pedra Bruta" primariamente representa?',
    options: [
      'A rocha material utilizada na fundação de edifícios profanos.',
      'O homem em seu estado de ignorância e imperfeições morais a serem lapidadas.',
      'A joia móvel utilizada exclusivamente pelo Venerável Mestre.',
      'O diploma de iniciação entregue ao neófito.',
    ],
    correctAnswer: '1',
    explanation: 'A Pedra Bruta é o símbolo primordial do próprio homem que busca desbastar suas paixões e vícios por meio do autoaperfeiçoamento.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_1_2',
    lessonId: 'inst_1_1',
    degreeNumber: 1,
    order: 2,
    type: 'multiple_choice',
    prompt: 'Qual faculdade humana é alegoricamente representada pelo "Maço" (ou Malhete)?',
    options: [
      'A inteligência passiva e a resignação.',
      'A erudição acadêmica e a vaidade intelectual.',
      'A Força de Vontade e a determinação perseverante do indivíduo.',
      'O poder judiciário de condenar os profanos.',
    ],
    correctAnswer: '2',
    explanation: 'O Maço representa a Força de Vontade firme e ativa indispensável para mover as energias transformadoras.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_1_3',
    lessonId: 'inst_1_1',
    degreeNumber: 1,
    order: 3,
    type: 'multiple_choice',
    prompt: 'O "Cinzel" atua em conjunto com o Maço representando qual princípio ético-filosófico?',
    options: [
      'A Razão e o Discernimento que direcionam a energia aplicada.',
      'A pressa na conclusão dos trabalhos em Loja.',
      'O temor reverencial diante das autoridades civis.',
      'A mera habilidade física muscular do operário.',
    ],
    correctAnswer: '0',
    explanation: 'Sem o Cinzel (Razão/Discernimento), a força cega do Maço destruiria a matéria bruta sem produzir uma forma útil e harmoniosa.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_1_4',
    lessonId: 'inst_1_1',
    degreeNumber: 1,
    order: 4,
    type: 'true_false',
    prompt: 'O trabalho do desbaste da Pedra Bruta cessa completamente logo após a cerimônia de Iniciação do Aprendiz.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '1',
    explanation: 'Falso. O desbaste da Pedra Bruta é um dever ininterrupto que acompanha o maçom durante toda a sua existência terrena.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_1_5',
    lessonId: 'inst_1_1',
    degreeNumber: 1,
    order: 5,
    type: 'true_false',
    prompt: 'O domínio das paixões desordenadas e o cultivo da virtude constituem os objetivos centrais do grau inicial.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. O Grau 1 foca estritamente na disciplina das paixões e purificação dos costumes.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_1_6',
    lessonId: 'inst_1_1',
    degreeNumber: 1,
    order: 6,
    type: 'multiple_choice',
    prompt: 'Onde o Aprendiz Maçom deve prioritariamente demonstrar a eficácia de sua lapidação moral?',
    options: [
      'Apenas nos discursos oratórios dentro das sessões do Templo.',
      'Em sua vida cotidiana: na família, no trabalho e na conduta perante a sociedade.',
      'Exclusivamente nas redes sociais através de debates doutrinários.',
      'Apenas nos banquetes ritualísticos da Ordem.',
    ],
    correctAnswer: '1',
    explanation: 'O templo interior do maçom reflete-se na sua retidão exemplar no convívio familiar, profissional e cívico.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_1_7',
    lessonId: 'inst_1_1',
    degreeNumber: 1,
    order: 7,
    type: 'multiple_choice',
    prompt: 'Qual destas atitudes é incompatível com o esforço de lapidação da Pedra Bruta?',
    options: [
      'A prática da paciência perante divergências de ideias.',
      'O cultivo da generosidade e auxílio ao necessitado.',
      'A soberba, o orgulho desmedido e a recusa em admitir os próprios erros.',
      'A pontualidade e o respeito aos deveres assumidos.',
    ],
    correctAnswer: '2',
    explanation: 'A soberba e a intransigência são as mais duras arestas que impedem a pedra de ser lapidada.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_1_8',
    lessonId: 'inst_1_1',
    degreeNumber: 1,
    order: 8,
    type: 'true_false',
    prompt: 'O Maço e o Cinzel devem ser empregados simultaneamente e em perfeito equilíbrio para se obter uma obra justa e perfeita.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. Vontade sem discernimento gera destruição; discernimento sem vontade gera estagnação inerte.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_1_9',
    lessonId: 'inst_1_1',
    degreeNumber: 1,
    order: 9,
    type: 'multiple_choice',
    prompt: 'A pedra desbastada pelo Aprendiz terá como destino futuro no Grau 2 transformar-se em quê?',
    options: [
      'Areia dispersa pelo vento.',
      'Pedra Cúbica polida, pronta para encaixar no edifício coletivo.',
      'Monumento esculpido para veneração pessoal.',
      'Bloco de mármore destinado ao comércio.',
    ],
    correctAnswer: '1',
    explanation: 'A Pedra Bruta lapidada torna-se a Pedra Cúbica no Grau de Companheiro, perfeitamente ajustada à construção do Templo Social.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_1_10',
    lessonId: 'inst_1_1',
    degreeNumber: 1,
    order: 10,
    type: 'written',
    prompt: 'Explique sucintamente (com suas próprias palavras) como a disciplina do pensamento e o controle da ira representam o manuseio prático do Maço e do Cinzel no cotidiano profano.',
    options: [],
    correctAnswer: 'Critério de correção do instrutor: O irmão deve demonstrar entendimento de que o controle da ira é a aplicação da Razão (Cinzel) guiada pela Força de Vontade (Maço) para moldar seu comportamento ético.',
    explanation: 'Avaliação discursiva corrigida pelo instrutor responsável.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- QUESTIONS FOR INSTRUCTION 1.2 (Estrutura do Templo e 3 Colunas) ---
  {
    id: 'q_1_2_1',
    lessonId: 'inst_1_2',
    degreeNumber: 1,
    order: 1,
    type: 'multiple_choice',
    prompt: 'Quais são as Três Grandes Colunas que simbolicamente sustentam o Templo Maçônico?',
    options: [
      'Fé, Esperança e Caridade.',
      'Sabedoria, Força e Beleza.',
      'Liberdade, Igualdade e Fraternidade.',
      'Prumo, Nível e Esquadro.',
    ],
    correctAnswer: '1',
    explanation: 'As três colunas emblemáticas de sustentação do Templo são a Sabedoria, a Força e a Beleza.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_2_2',
    lessonId: 'inst_1_2',
    degreeNumber: 1,
    order: 2,
    type: 'multiple_choice',
    prompt: 'Qual é o papel atribuído à coluna da "Sabedoria"?',
    options: [
      'Adornar as paredes externas do Templo.',
      'Conceber, planejar e arquitetar obras com justiça e harmonia.',
      'Impor castigos físicos aos que violam as regras.',
      'Acumular riquezas financeiras para o patrimônio.',
    ],
    correctAnswer: '1',
    explanation: 'A Sabedoria é responsável pela concepção judiciosa de todos os planos e edificações morais.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_2_3',
    lessonId: 'inst_1_2',
    degreeNumber: 1,
    order: 3,
    type: 'multiple_choice',
    prompt: 'A coluna da "Força" possui qual função simbólica primordial?',
    options: [
      'Sustentar, manter e defender vigorosamente as resoluções virtuosas assumidas.',
      'Subjugar as pessoas que discordam dos nossos pontos de vista.',
      'Construir armas materiais de combate.',
      'Representar a autoridade monárquica absoluta.',
    ],
    correctAnswer: '0',
    explanation: 'A Força sustenta os alicerces morais da Ordem e confere resiliência aos irmãos diante das adversidades.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_2_4',
    lessonId: 'inst_1_2',
    degreeNumber: 1,
    order: 4,
    type: 'multiple_choice',
    prompt: 'O que a coluna da "Beleza" traz para a sustentação do Templo?',
    options: [
      'Gastar recursos em adornos efêmeros.',
      'Harmonizar os ânimos e adornar a convivência humana com decência e arte.',
      'Impedir o ingresso de pessoas simples.',
      'Definir a cor dos trajes obrigatórios.',
    ],
    correctAnswer: '1',
    explanation: 'A Beleza adorna as ações e harmoniza a convivência fraterna entre os seres humanos.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_2_5',
    lessonId: 'inst_1_2',
    degreeNumber: 1,
    order: 5,
    type: 'true_false',
    prompt: 'A orientação clássica do Templo Maçônico estende-se simbolicamente do Ocidente ao Oriente.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. O caminho iniciático parte do Ocidente (trevas da ignorância) rumo ao Oriente (fonte da Luz).',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_2_6',
    lessonId: 'inst_1_2',
    degreeNumber: 1,
    order: 6,
    type: 'true_false',
    prompt: 'No Templo Maçônico, as dimensões infinitas simbolizam a universalidade da fraternidade e do amor ao próximo.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. As dimensões cósmicas do Templo lembram que a caridade e a moral maçônicas não conhecem fronteiras geográficas.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_2_7',
    lessonId: 'inst_1_2',
    degreeNumber: 1,
    order: 7,
    type: 'multiple_choice',
    prompt: 'Qual personagem tradicional da Sabedoria é historicamente associado à coluna homônima?',
    options: [
      'Salomão (o Rei sábio).',
      'Hiram de Tiro (o Rei vigoroso).',
      'Hiram Abiff (o mestre artífice da beleza).',
      'Pitágoras de Samos.',
    ],
    correctAnswer: '0',
    explanation: 'Salomão representa o ideal da Sabedoria governativa e inspiradora.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_2_8',
    lessonId: 'inst_1_2',
    degreeNumber: 1,
    order: 8,
    type: 'true_false',
    prompt: 'Uma edificação só é perfeita quando há equilíbrio entre a concepção (Sabedoria), a sustentação (Força) e a harmonia estética (Beleza).',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. A ausência de qualquer uma das três colunas desestabiliza a integridade do edifício moral.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_2_9',
    lessonId: 'inst_1_2',
    degreeNumber: 1,
    order: 9,
    type: 'multiple_choice',
    prompt: 'Em termos éticos pessoais, como o maçom cultiva a "Coluna da Beleza"?',
    options: [
      'Comprando objetos caros e exibindo-os publicamente.',
      'Sendo polido no trato, amável nas palavras e digno nas ações fraternas.',
      'Ignorando os problemas da comunidade.',
      'Julgando os outros apenas pela aparência física.',
    ],
    correctAnswer: '1',
    explanation: 'A verdadeira beleza reside na nobreza dos sentimentos, na pureza da linguagem e na generosidade de espírito.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_2_10',
    lessonId: 'inst_1_2',
    degreeNumber: 1,
    order: 10,
    type: 'written',
    prompt: 'Descreva como um líder ou gestor pode equilibrar Sabedoria, Força e Beleza ao administrar conflitos interpessoais em um ambiente profissional ou fraternal.',
    options: [],
    correctAnswer: 'Critério de correção: O irmão deve apresentar como a Sabedoria guia a análise imparcial dos fatos, a Força sustenta a aplicação de princípios éticos justos sem vacilar, e a Beleza assegura empatia, respeito e concórdia.',
    explanation: 'Avaliação discursiva corrigida pelo instrutor responsável.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- QUESTIONS FOR INSTRUCTION 1.3 (O Silêncio e a Disciplina) ---
  {
    id: 'q_1_3_1',
    lessonId: 'inst_1_3',
    degreeNumber: 1,
    order: 1,
    type: 'multiple_choice',
    prompt: 'Por que o silêncio é a primeira grande disciplina imposta ao Aprendiz?',
    options: [
      'Para punir o neófito por sua condição de recém-chegado.',
      'Para ensiná-lo a ouvir com atenção, meditar com profundidade e controlar a impulsividade verbal.',
      'Porque Aprendizes não possuem inteligência suficiente para opinar.',
      'Para evitar que o trabalho ritualístico termine mais tarde.',
    ],
    correctAnswer: '1',
    explanation: 'O silêncio desenvolve a introspecção profunda, a escuta atenta e o autodomínio mental.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_3_2',
    lessonId: 'inst_1_3',
    degreeNumber: 1,
    order: 2,
    type: 'true_false',
    prompt: 'A escola filosófica de Pitágoras impunha aos discípulos neófitos anos de rigoroso silêncio e escuta antes de lhes permitir indagações.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. O silêncio pitagórico dos acusmáticos serviu de inspiração direta para a tradição iniciática ocidental.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_3_3',
    lessonId: 'inst_1_3',
    degreeNumber: 1,
    order: 3,
    type: 'multiple_choice',
    prompt: 'Qual coluna o Aprendiz ocupa primordialmente no Templo em razão de seu estágio de aprendizado?',
    options: [
      'A Coluna do Sul, sob a luz intensa do meio-dia.',
      'A Coluna do Norte, onde a luz é suave e propícia à meditação e recolhimento.',
      'O Trono do Oriente ao lado do Venerável.',
      'O centro exato do Pavimento Mosaico.',
    ],
    correctAnswer: '1',
    explanation: 'A Coluna do Norte acolhe os Aprendizes, oferecendo um ambiente reservado para absorção gradual da claridade iniciática.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_3_4',
    lessonId: 'inst_1_3',
    degreeNumber: 1,
    order: 4,
    type: 'true_false',
    prompt: 'O silêncio maçônico significa passividade covarde diante de injustiças flagrantes.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '1',
    explanation: 'Falso. O silêncio é instrumento de amadurecimento interior; diante da injustiça ou opressão, o maçom tem o dever ético de agir com coragem e retidão.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_3_5',
    lessonId: 'inst_1_3',
    degreeNumber: 1,
    order: 5,
    type: 'multiple_choice',
    prompt: 'Qual benefício a prática reflexiva do silêncio traz para a comunicação interpessoal?',
    options: [
      'Isolamento total e rejeição da vida em sociedade.',
      'Capacidade de escutar com empatia antes de formular respostas precipitadas.',
      'Esquecimento das regras de convivência.',
      'Aumento da ansiedade ao conversar.',
    ],
    correctAnswer: '1',
    explanation: 'A escuta reflexiva dissipa mal-entendidos e enriquece o diálogo fraterno e civilizado.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_3_6',
    lessonId: 'inst_1_3',
    degreeNumber: 1,
    order: 6,
    type: 'true_false',
    prompt: 'Saber guardar discrição sobre os assuntos internos e sobre a intimidade dos irmãos é um compromisso solene de todo iniciado.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. A discrição e a lealdade fraterna são pilares fundamentais da confiança mútua na Ordem.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_3_7',
    lessonId: 'inst_1_3',
    degreeNumber: 1,
    order: 7,
    type: 'multiple_choice',
    prompt: 'Em momentos de forte provocação ou discórdia, a melhor postura inicial do Aprendiz é:',
    options: [
      'Responder imediatamente com agressividade redobrada.',
      'Recorrer ao silêncio reflexivo para acalmar as emoções e ponderar a resposta justa.',
      'Abandonar a Loja e difamar os irmãos.',
      'Espalhar fofocas entre conhecidos profanos.',
    ],
    correctAnswer: '1',
    explanation: 'O freio da língua e a serenidade da mente evitam que conflitos pequenos se tornem tragédias morais.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_3_8',
    lessonId: 'inst_1_3',
    degreeNumber: 1,
    order: 8,
    type: 'true_false',
    prompt: 'O domínio da palavra começa necessariamente pelo domínio do silêncio.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. Quem não domina o ato de calar não domina o que profere.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_3_9',
    lessonId: 'inst_1_3',
    degreeNumber: 1,
    order: 9,
    type: 'multiple_choice',
    prompt: 'O compromisso fraterno firmado pelo Aprendiz perante a Ordem implica em:',
    options: [
      'Priorizar interesses egoístas em detrimento do grupo.',
      'Socorrer e amparar os irmãos em suas justas necessidades e defender a honra da Instituição.',
      'Esperar vantagens materiais e financeiras imediatas.',
      'Não se preocupar com os estudos propostos.',
    ],
    correctAnswer: '1',
    explanation: 'A fraternidade é o socorro mútuo nas horas de aflição e o apoio no aperfeiçoamento moral.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_1_3_10',
    lessonId: 'inst_1_3',
    degreeNumber: 1,
    order: 10,
    type: 'written',
    prompt: 'Comente de que maneira a disciplina do silêncio contribui para a elevação moral do Aprendiz perante os ruídos e conflitos do mundo moderno.',
    options: [],
    correctAnswer: 'Critério de correção: O irmão deve ressaltar que o silêncio funciona como escudo protetor contra o imediatismo das redes sociais, julgamentos precipitados e reações emocionais tóxicas.',
    explanation: 'Avaliação discursiva corrigida pelo instrutor responsável.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- QUESTIONS FOR INSTRUCTION 2.1 (Estrela Flamígera e Letra G) ---
  {
    id: 'q_2_1_1',
    lessonId: 'inst_2_1',
    degreeNumber: 2,
    order: 1,
    type: 'multiple_choice',
    prompt: 'Quantas pontas possui a Estrela Flamígera que ilumina os trabalhos do Companheiro Maçom?',
    options: ['3 pontas.', '4 pontas.', '5 pontas (Pentagrama).', '6 pontas (Hexagrama).'],
    correctAnswer: '2',
    explanation: 'A Estrela Flamígera é um pentagrama (5 pontas), símbolo do homem iluminado pelo intelecto e pela moral.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_1_2',
    lessonId: 'inst_2_1',
    degreeNumber: 2,
    order: 2,
    type: 'multiple_choice',
    prompt: 'Qual letra sagrada situa-se no centro da Estrela Flamígera do Grau de Companheiro?',
    options: ['Letra A.', 'Letra G.', 'Letra M.', 'Letra T.'],
    correctAnswer: '1',
    explanation: 'A letra G brilha no centro da Estrela Flamígera, evocando Geometria, Geração, Gravitação, Gênio e Gnose.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_1_3',
    lessonId: 'inst_2_1',
    degreeNumber: 2,
    order: 3,
    type: 'true_false',
    prompt: 'A Geometria é considerada a ciência mais nobre dos Antigos Construtores, constituindo a base de toda a arquitetura operativa e especulativa.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. A Geometria rege as proporções e a harmonia das formas no universo.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_1_4',
    lessonId: 'inst_2_1',
    degreeNumber: 2,
    order: 4,
    type: 'multiple_choice',
    prompt: 'O Pentagrama da Estrela Flamígera relaciona-se simbolicamente com:',
    options: [
      'Os cinco sentidos humanos purificados e o Homem de Vitrúvio em equilíbrio.',
      'As cinco estações do ano lunar.',
      'Os cinco continentes geográficos do planeta.',
      'Os cinco votos do monasticismo medieval.',
    ],
    correctAnswer: '0',
    explanation: 'O pentagrama expressa o microcosmo humano: cabeça, braços e pernas em perfeito equilíbrio dinâmico.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_1_5',
    lessonId: 'inst_2_1',
    degreeNumber: 2,
    order: 5,
    type: 'true_false',
    prompt: 'A palavra "Geração", vinculada à letra G, refere-se unicamente à procriação física de herdeiros biológicos.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '1',
    explanation: 'Falso. Refere-se à geração contínua de ideias nobres, virtudes, obras de arte e progresso espiritual.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_1_6',
    lessonId: 'inst_2_1',
    degreeNumber: 2,
    order: 6,
    type: 'multiple_choice',
    prompt: 'Qual é o papel da "Gravitação" no sentido filosófico maçônico?',
    options: [
      'Impedir que os maçons viajem para outros países.',
      'A força de atração fraterna e amor universal que une os homens em uma só família.',
      'A obrigação de carregar pedras pesadas.',
      'O peso das penalidades regulamentares.',
    ],
    correctAnswer: '1',
    explanation: 'Assim como a gravidade física mantém os astros em harmonia, a atração do Amor Fraternal mantém os homens em concórdia.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_1_7',
    lessonId: 'inst_2_1',
    degreeNumber: 2,
    order: 7,
    type: 'true_false',
    prompt: 'A palavra "Gnose" denota a busca do conhecimento iluminador e consciente da verdade e do papel humano na Criação.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. Gnose é o conhecimento profundo e transformador que liberta a mente.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_1_8',
    lessonId: 'inst_2_1',
    degreeNumber: 2,
    order: 8,
    type: 'multiple_choice',
    prompt: 'Ao contemplar a Estrela Flamígera, o Companheiro deve se recordar de que:',
    options: [
      'Sua jornada de estudos já está completa e nada mais há a aprender.',
      'Ele deve ser uma fonte irradiadora de luz, retidão e conhecimento para seus semelhantes.',
      'Ele possui superioridade inquestionável sobre todas as outras pessoas.',
      'A luz deve ser guardada apenas para benefício individual e egoísta.',
    ],
    correctAnswer: '1',
    explanation: 'A chama da estrela incita o Companheiro a iluminar o mundo com suas virtudes e conhecimentos.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_1_9',
    lessonId: 'inst_2_1',
    degreeNumber: 2,
    order: 9,
    type: 'true_false',
    prompt: 'O Companheiro Maçom tem o dever de investigar a natureza das ciências e enriquecer sua mente com conhecimentos úteis à humanidade.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. O Grau 2 é o grau por excelência do estudo científico e filosófico das artes liberais.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_1_10',
    lessonId: 'inst_2_1',
    degreeNumber: 2,
    order: 10,
    type: 'written',
    prompt: 'Discorra sobre como a simbologia da Letra G (Geometria, Gênio e Geração) inspira o Companheiro a atuar como um agente criativo e transformador em sua comunidade.',
    options: [],
    correctAnswer: 'Critério de correção: O irmão deve correlacionar a Geometria com a ordem e planejamento, o Gênio com a criatividade inovadora e a Geração com a capacidade de produzir obras e legados benéficos para a sociedade.',
    explanation: 'Avaliação discursiva corrigida pelo instrutor responsável.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- QUESTIONS FOR INSTRUCTION 2.2 (Sete Artes Liberais) ---
  {
    id: 'q_2_2_1',
    lessonId: 'inst_2_2',
    degreeNumber: 2,
    order: 1,
    type: 'multiple_choice',
    prompt: 'As Sete Artes e Ciências Liberais dividem-se classicamente em quais dois ramos pedagógicos?',
    options: [
      'Trivium e Quadrivium.',
      'Física e Metafísica.',
      'Antigo e Novo Testamento.',
      'Direito Romano e Direito Canônico.',
    ],
    correctAnswer: '0',
    explanation: 'O Trivium (3 artes da linguagem) e o Quadrivium (4 ciências dos números e formas).',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_2_2',
    lessonId: 'inst_2_2',
    degreeNumber: 2,
    order: 2,
    type: 'multiple_choice',
    prompt: 'Quais são as três disciplinas que compõem o "Trivium"?',
    options: [
      'Gramática, Lógica e Retórica.',
      'Aritmética, Geometria e Música.',
      'Física, Química e Biologia.',
      'História, Geografia e Filosofia.',
    ],
    correctAnswer: '0',
    explanation: 'O Trivium capacita o homem a dominar a expressão correta (Gramática), o raciocínio válido (Lógica) e a persuasão ética (Retórica).',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_2_3',
    lessonId: 'inst_2_2',
    degreeNumber: 2,
    order: 3,
    type: 'multiple_choice',
    prompt: 'Quais são as quatro disciplinas que compõem o "Quadrivium"?',
    options: [
      'Aritmética, Geometria, Música e Astronomia.',
      'Poesia, Escultura, Pintura e Arquitetura.',
      'Medicina, Farmácia, Engenharia e Teologia.',
      'Política, Economia, Sociologia e Antropologia.',
    ],
    correctAnswer: '0',
    explanation: 'O Quadrivium estuda a manifestação dos números no espaço, no tempo e no cosmos.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_2_4',
    lessonId: 'inst_2_2',
    degreeNumber: 2,
    order: 4,
    type: 'true_false',
    prompt: 'A disciplina da Lógica (ou Dialética) tem como objetivo principal ensinar a identificar falácias e estruturar pensamentos válidos.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. A lógica protege o intelecto contra enganos e ilusões sofísticas.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_2_5',
    lessonId: 'inst_2_2',
    degreeNumber: 2,
    order: 5,
    type: 'true_false',
    prompt: 'A Retórica maçônica visa manipular as emoções alheias a qualquer custo, mesmo mentindo.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '1',
    explanation: 'Falso. A verdadeira retórica clássica é a arte de colocar a eloquência e a beleza do verbo a serviço estrito da Verdade e da Justiça.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_2_6',
    lessonId: 'inst_2_2',
    degreeNumber: 2,
    order: 6,
    type: 'multiple_choice',
    prompt: 'No Quadrivium, a "Música" é entendida pelos filósofos antigos como:',
    options: [
      'Apenas mero passatempo para festividades profanas.',
      'A aplicação da proporção matemática e harmonia sonora ao longo do tempo.',
      'Uma atividade desprovida de regras racionais.',
      'A repetição de ruídos sem qualquer escala tonal.',
    ],
    correctAnswer: '1',
    explanation: 'Para Pitágoras e os clássicos, a Música é a ciência dos números expressa em intervalos de harmonia sonora e consonância cósmica.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_2_7',
    lessonId: 'inst_2_2',
    degreeNumber: 2,
    order: 7,
    type: 'true_false',
    prompt: 'A Astronomia convida o Companheiro a contemplar a grandiosidade da ordem universal e das leis cósmicas.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. A astronomia expande a consciência perante as leis imutáveis do Grande Arquiteto do Universo.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_2_8',
    lessonId: 'inst_2_2',
    degreeNumber: 2,
    order: 8,
    type: 'multiple_choice',
    prompt: 'Por que o estudo das Artes Liberais é indispensável para o combate ao obscurantismo?',
    options: [
      'Porque torna o maçom imune a qualquer fiscalização da lei.',
      'Porque desenvolve o pensamento crítico, a autonomia intelectual e a resistência à desinformação.',
      'Porque substitui a necessidade de trabalhar.',
      'Porque garante títulos honoríficos automáticos na política profana.',
    ],
    correctAnswer: '1',
    explanation: 'O homem instruído nas artes da razão não é facilmente manipulado por demagogos e fanatismos.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_2_9',
    lessonId: 'inst_2_2',
    degreeNumber: 2,
    order: 9,
    type: 'true_false',
    prompt: 'O Companheiro Maçom deve encerrar seus estudos acadêmicos e intelectuais assim que recebe o respectivo diploma de aumento de salário.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '1',
    explanation: 'Falso. A elevação de grau é o início de um compromisso redobrado com a pesquisa, leitura e erudição virtuosa.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_2_10',
    lessonId: 'inst_2_2',
    degreeNumber: 2,
    order: 10,
    type: 'written',
    prompt: 'Como a união entre a Lógica (Trivium) e a Geometria (Quadrivium) pode auxiliar o Companheiro a estruturar projetos práticos de filantropia e melhoria social em sua região?',
    options: [],
    correctAnswer: 'Critério de correção: O irmão deve enfatizar que a Lógica propicia o diagnóstico lúcido e sem ilusões dos problemas reais, enquanto a Geometria oferece o método de planejamento estruturado, proporção de recursos e execução sustentável.',
    explanation: 'Avaliação discursiva corrigida pelo instrutor responsável.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- QUESTIONS FOR INSTRUCTION 2.3 (Alavanca, Nível e Prumo) ---
  {
    id: 'q_2_3_1',
    lessonId: 'inst_2_3',
    degreeNumber: 2,
    order: 1,
    type: 'multiple_choice',
    prompt: 'O "Nível" é um instrumento de trabalho que simboliza primariamente qual princípio fundamental?',
    options: [
      'A autoridade suprema dos ricos sobre os pobres.',
      'A Igualdade fundamental de todos os seres humanos em dignidade e direitos.',
      'A destruição de todas as leis civis.',
      'A preferência por indivíduos de determinado grupo.',
    ],
    correctAnswer: '1',
    explanation: 'O Nível nos lembra que todos os homens nascem iguais e viajam no mesmo nível em direção ao horizonte comum.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_3_2',
    lessonId: 'inst_2_3',
    degreeNumber: 2,
    order: 2,
    type: 'multiple_choice',
    prompt: 'O "Prumo" (ou Perpendicular) ensina ao iniciado a virtude da:',
    options: [
      'Flexibilidade moral oportunista.',
      'Retidão de caráter, integridade e elevação espiritual inabalável.',
      'Curvatura diante dos poderosos do mundo.',
      'Inércia e falta de posicionamento ético.',
    ],
    correctAnswer: '1',
    explanation: 'O Prumo representa a linha vertical inquebrantável da retidão moral e da justiça.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_3_3',
    lessonId: 'inst_2_3',
    degreeNumber: 2,
    order: 3,
    type: 'multiple_choice',
    prompt: 'Qual ferramenta mecânica é conferida ao Companheiro simbolizando a multiplicação de forças em prol do bem coletivo?',
    options: ['A Espada.', 'A Alavanca.', 'O Escudo.', 'A Foice.'],
    correctAnswer: '1',
    explanation: 'A Alavanca é a ferramenta que multiplica a força do homem, permitindo erguer fardos pesados que o esforço isolado não moveria.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_3_4',
    lessonId: 'inst_2_3',
    degreeNumber: 2,
    order: 4,
    type: 'true_false',
    prompt: 'Para que a Alavanca funcione eficazmente, ela necessita de um ponto de apoio firme, que na Maçonaria é representado pela Fraternidade e pela Justiça.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. A Fraternidade é o ponto de apoio que torna o esforço conjunto capaz de transformar realidades difíceis.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_3_5',
    lessonId: 'inst_2_3',
    degreeNumber: 2,
    order: 5,
    type: 'true_false',
    prompt: 'O Nível e o Prumo se opõem diametralmente e não podem coexistir nas ações de um mesmo maçom.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '1',
    explanation: 'Falso. O Nível (horizontalidade/igualdade) e o Prumo (verticalidade/retidão) unem-se no Esquadro perfeito para guiar a conduta.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_3_6',
    lessonId: 'inst_2_3',
    degreeNumber: 2,
    order: 6,
    type: 'multiple_choice',
    prompt: 'A Régua de 24 polegadas ensina a sábia distribuição de qual recurso precioso?',
    options: [
      'Do ouro e das pratas acumuladas.',
      'Do Tempo de vida, dividindo as horas entre o dever, o estudo, o descanso e a caridade.',
      'Dos títulos de propriedade de terras.',
      'Das punições aplicadas aos infratores.',
    ],
    correctAnswer: '1',
    explanation: 'As 24 divisões da Régua simbolizam as 24 horas do dia, ensinando a disciplina e o aproveitamento digno do tempo.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_3_7',
    lessonId: 'inst_2_3',
    degreeNumber: 2,
    order: 7,
    type: 'true_false',
    prompt: 'Agir com retidão (Prumo) e tratar todos com igual consideração (Nível) são exigências indeclináveis para a harmonia em qualquer Loja.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. O respeito igualitário e a retidão mantêm a paz e a concórdia entre os obreiros.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_3_8',
    lessonId: 'inst_2_3',
    degreeNumber: 2,
    order: 8,
    type: 'multiple_choice',
    prompt: 'Quando um Companheiro se depara com um irmão em dificuldades morais ou financeiras, o uso da "Alavanca fraterna" consiste em:',
    options: [
      'Espalhar a situação para terceiros a título de curiosidade.',
      'Oferecer amparo solidário, orientação lúcida e esforço conjunto para reerguê-lo.',
      'Afastar-se imediatamente para não se envolver.',
      'Exigir garantias materiais antes de qualquer palavra de conforto.',
    ],
    correctAnswer: '1',
    explanation: 'A solidariedade ativa e o amparo desinteressado são a personificação da Alavanca em ação.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_3_9',
    lessonId: 'inst_2_3',
    degreeNumber: 2,
    order: 9,
    type: 'true_false',
    prompt: 'A Pedra Cúbica polida pelo Companheiro encaixa-se sem necessidade de cimento ou argamassa porque foi talhada com perfeita geometria.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. A perfeição do ajuste moral entre homens virtuosos dispensa artifícios forçados de coerção.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_2_3_10',
    lessonId: 'inst_2_3',
    degreeNumber: 2,
    order: 10,
    type: 'written',
    prompt: 'Explique como a associação do Nível (Igualdade), Prumo (Retidão) e Alavanca (Solidariedade) orienta o maçom a combater preconceitos e discriminações no meio social.',
    options: [],
    correctAnswer: 'Critério de correção: O irmão deve apontar que o Nível impede que o maçom se julgue superior a outrem por etnia, classe ou crença; o Prumo garante que sua postura seja irrepreensível; e a Alavanca impulsiona ações práticas de acolhimento e defesa dos vulneráveis.',
    explanation: 'Avaliação discursiva corrigida pelo instrutor responsável.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- QUESTIONS FOR INSTRUCTION 3.1 (Lenda de Hiram Abiff) ---
  {
    id: 'q_3_1_1',
    lessonId: 'inst_3_1',
    degreeNumber: 3,
    order: 1,
    type: 'multiple_choice',
    prompt: 'Quem é a figura arquetípica central da Lenda Tradicional do Grau de Mestre Maçom?',
    options: ['O Rei Salomão.', 'O Mestre Hiram Abiff.', 'O filósofo Sócrates.', 'O Rei Davi.'],
    correctAnswer: '1',
    explanation: 'Hiram Abiff é o Mestre Arquiteto cuja fidelidade inabalável aos princípios éticos é o cerne do Terceiro Grau.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_1_2',
    lessonId: 'inst_3_1',
    degreeNumber: 3,
    order: 2,
    type: 'multiple_choice',
    prompt: 'Quais são os três grandes vícios personificados pelos algozes na narrativa tradicional do Grau 3?',
    options: [
      'A Preguiça, a Gula e a Avareza.',
      'A Ignorância, o Fanatismo e a Ambição.',
      'A Tristeza, o Medo e a Dúvida.',
      'A Pobreza, a Enfermidade e a Velhice.',
    ],
    correctAnswer: '1',
    explanation: 'Os três algozes simbolizam as três maiores ameaças morais à sociedade: Ignorância, Fanatismo e Ambição desmedida.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_1_3',
    lessonId: 'inst_3_1',
    degreeNumber: 3,
    order: 3,
    type: 'true_false',
    prompt: 'A Lenda de Hiram ensina que a integridade e a fidelidade aos compromissos da consciência devem prevalecer mesmo sob ameaça à própria vida física.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. O valor supremo do Mestre reside na honra inegociável de sua palavra e integridade.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_1_4',
    lessonId: 'inst_3_1',
    degreeNumber: 3,
    order: 4,
    type: 'multiple_choice',
    prompt: 'O primeiro algoz (a Ignorância) golpeia a vítima em qual parte do corpo simbólico?',
    options: [
      'Na garganta (onde residem as palavras impensadas e o juízo sem saber).',
      'No pé esquerdo.',
      'Na mão direita.',
      'Nas costas.',
    ],
    correctAnswer: '0',
    explanation: 'A Ignorância agride a garganta, sufocando a verdade e emitindo julgamentos precipitados.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_1_5',
    lessonId: 'inst_3_1',
    degreeNumber: 3,
    order: 5,
    type: 'multiple_choice',
    prompt: 'O segundo algoz (o Fanatismo) golpeia qual centro vital, cegando os sentimentos nobres?',
    options: ['O peito / coração.', 'O joelho.', 'A ponta dos dedos.', 'O ombro.'],
    correctAnswer: '0',
    explanation: 'O Fanatismo atinge o coração, corrompendo os sentimentos de fraternidade e substituindo o amor pelo ódio dogmático.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_1_6',
    lessonId: 'inst_3_1',
    degreeNumber: 3,
    order: 6,
    type: 'multiple_choice',
    prompt: 'O terceiro algoz (a Ambição) desfere o golpe fatal em qual centro do discernimento?',
    options: ['Na testa / cabeça.', 'No calcanhar.', 'No cotovelo.', 'Na cintura.'],
    correctAnswer: '0',
    explanation: 'A Ambição fere a fronte, destruindo a razão e a lucidez intelectual em busca de vantagens egoístas.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_1_7',
    lessonId: 'inst_3_1',
    degreeNumber: 3,
    order: 7,
    type: 'true_false',
    prompt: 'A transmutação vivenciada pelo Mestre representa a morte do homem profano e o despertar para uma vida de sabedoria e responsabilidade superior.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. O renascimento simbólico consagra o iniciado na maturidade do Terceiro Grau.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_1_8',
    lessonId: 'inst_3_1',
    degreeNumber: 3,
    order: 8,
    type: 'true_false',
    prompt: 'Um Mestre Maçom está autorizado a praticar o fanatismo desde que seja em defesa exclusiva de sua própria Loja.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '1',
    explanation: 'Falso. O fanatismo é expressamente banido da filosofia maçônica em todas as suas manifestações.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_1_9',
    lessonId: 'inst_3_1',
    degreeNumber: 3,
    order: 9,
    type: 'multiple_choice',
    prompt: 'A "Câmara do Meio" onde os Mestres se reúnem representa simbolicamente:',
    options: [
      'Um local de descanso sem qualquer estudo.',
      'O centro interior da consciência, onde reina a luz do discernimento e a comunhão dos sábios.',
      'Uma sala secreta de armazenamento de ouro material.',
      'Um tribunal de inquisição para condenar profanos.',
    ],
    correctAnswer: '1',
    explanation: 'A Câmara do Meio é o espaço sagrado da razão serena e da governança fraterna.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_1_10',
    lessonId: 'inst_3_1',
    degreeNumber: 3,
    order: 10,
    type: 'written',
    prompt: 'Analise detalhadamente como o Fanatismo e a Ambição operam na contemporaneidade (por exemplo, na política ou na comunicação) e como o Mestre Maçom deve se portar para neutralizar essas duas forças destrutivas.',
    options: [],
    correctAnswer: 'Critério de correção: O irmão deve evidenciar que o Fanatismo divide pessoas por meio de radicalismos intransigentes, e a Ambição sacrifica o bem comum por vaidades momentâneas. O Mestre responde com tolerância, diálogo equilibrado, compromisso ético e serenidade.',
    explanation: 'Avaliação discursiva corrigida pelo instrutor responsável.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- QUESTIONS FOR INSTRUCTION 3.2 (O Ramo de Acácia) ---
  {
    id: 'q_3_2_1',
    lessonId: 'inst_3_2',
    degreeNumber: 3,
    order: 1,
    type: 'multiple_choice',
    prompt: 'Por que a Acácia foi escolhida na tradição como símbolo emblemático do Terceiro Grau?',
    options: [
      'Por ser uma planta comum de baixo custo.',
      'Por possuir madeira incorruptível e folhas que resistem perenes, simbolizando a imortalidade da alma e a pureza moral.',
      'Porque suas flores exalam perfumes tóxicos.',
      'Por ser uma árvore cultivada apenas na Europa.',
    ],
    correctAnswer: '1',
    explanation: 'A Acácia representa a incorruptibilidade da virtude e a perenidade dos ideais nobres.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_2_2',
    lessonId: 'inst_3_2',
    degreeNumber: 3,
    order: 2,
    type: 'true_false',
    prompt: 'A expressão "A Acácia me é conhecida" atesta que o irmão atingiu a plenitude do Grau de Mestre e reconhece o valor perene do espírito sobre a matéria.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. O conhecimento da Acácia é a chave de identificação do verdadeiro Mestre Maçom.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_2_3',
    lessonId: 'inst_3_2',
    degreeNumber: 3,
    order: 3,
    type: 'multiple_choice',
    prompt: 'A imortalidade ensinada no Grau de Mestre manifesta-se concretamente na história dos homens através:',
    options: [
      'Da preservação de estátuas de mármore com seu nome.',
      'Do legado perene de virtude, justiça, caridade e conhecimento deixado para a posteridade.',
      'Do acúmulo de heranças materiais bancárias.',
      'Da tentativa de viver indefinidamente na carne.',
    ],
    correctAnswer: '1',
    explanation: 'As obras altruístas e o amor dedicado aos semelhantes permanecem vivos na memória e no coração das futuras gerações.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_2_4',
    lessonId: 'inst_3_2',
    degreeNumber: 3,
    order: 4,
    type: 'true_false',
    prompt: 'Diante das perdas e transições inevitáveis da existência, o ramo de Acácia infunde no Mestre a esperança serena no triunfo final da Luz e da Vida.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. A Acácia é o estandarte da esperança que consola e fortalece o espírito.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_2_5',
    lessonId: 'inst_3_2',
    degreeNumber: 3,
    order: 5,
    type: 'multiple_choice',
    prompt: 'Qual destas atitudes demonstra que um irmão verdadeiramente "conhece a Acácia"?',
    options: [
      'Agir com integridade mesmo quando ninguém está olhando e manter a retidão sob qualquer prova.',
      'Cobrar honorários excessivos dos próprios irmãos.',
      'Fugir dos compromissos e culpar terceiros pelos próprios erros.',
      'Vangloriar-se publicamente de suas doações de caridade.',
    ],
    correctAnswer: '0',
    explanation: 'A incorruptibilidade moral interna é a marca indelével de quem conhece a Acácia.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_2_6',
    lessonId: 'inst_3_2',
    degreeNumber: 3,
    order: 6,
    type: 'true_false',
    prompt: 'A madeira da Acácia era historicamente utilizada pelos antigos hebreus na confecção da Arca da Aliança e dos objetos sagrados do Tabernáculo.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. A madeira de cetim/acácia (shittah) era prescrita para a construção do Tabernáculo por sua durabilidade e pureza.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_2_7',
    lessonId: 'inst_3_2',
    degreeNumber: 3,
    order: 7,
    type: 'multiple_choice',
    prompt: 'O ramo verdejante brotando sobre a terra sinaliza que:',
    options: [
      'A matéria sepultada foi esquecida para sempre.',
      'A vida e a virtude renascem triunfantes sobre a escuridão.',
      'É necessário parar de trabalhar e esperar passivamente.',
      'A natureza deve ser destruída para fins comerciais.',
    ],
    correctAnswer: '1',
    explanation: 'O verde vivo da Acácia simboliza a vitória perpétua da regeneração sobre o desânimo e a morte.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_2_8',
    lessonId: 'inst_3_2',
    degreeNumber: 3,
    order: 8,
    type: 'true_false',
    prompt: 'Para o Mestre Maçom, o medo da morte física é superado pela consciência de ter cumprido retamente seu dever perante a humanidade e o GADU.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. A tranquilidade da consciência justa dissipa qualquer temor existencial.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_2_9',
    lessonId: 'inst_3_2',
    degreeNumber: 3,
    order: 9,
    type: 'multiple_choice',
    prompt: 'O Mestre que vive em conformidade com o simbolismo da Acácia pauta suas relações por:',
    options: [
      'Honestidade inegociável, generosidade fraterna e busca perene da harmonia.',
      'Rancores acumulados e vinganças calculadas.',
      'Desprezo pelos mais jovens e recém-chegados.',
      'Busca de privilégios financeiros indevidos.',
    ],
    correctAnswer: '0',
    explanation: 'A pureza e generosidade refletem a perenidade da folha da Acácia.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_2_10',
    lessonId: 'inst_3_2',
    degreeNumber: 3,
    order: 10,
    type: 'written',
    prompt: 'Explique a relação filosófica entre o ramo de Acácia, a imortalidade do pensamento ético e o legado que o Mestre Maçom deve construir para sua família e comunidade.',
    options: [],
    correctAnswer: 'Critério de correção: O irmão deve explanar que o corpo é efêmero, mas o caráter, os ensinamentos transmitidos aos filhos e o trabalho de solidariedade na comunidade constituem a verdadeira imortalidade simbolizada pela Acácia.',
    explanation: 'Avaliação discursiva corrigida pelo instrutor responsável.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- QUESTIONS FOR INSTRUCTION 3.3 (Câmara do Meio e a Mestria) ---
  {
    id: 'q_3_3_1',
    lessonId: 'inst_3_3',
    degreeNumber: 3,
    order: 1,
    type: 'multiple_choice',
    prompt: 'Qual é o principal dever do Mestre Maçom perante os Aprendizes e Companheiros de sua Loja?',
    options: [
      'Ignorá-los e permitir que descubram tudo sozinhos sem qualquer apoio.',
      'Atuar como mentor generoso, transmitindo com paciência e exemplo vivo as instruções e a moral da Ordem.',
      'Exigir que lhe prestem vassalagem e tarefas domésticas.',
      'Impedir que avancem nos estudos.',
    ],
    correctAnswer: '1',
    explanation: 'A vocação máxima do Mestre é a docência, a mentoria fraterna e o exemplo condutor para as novas gerações.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_3_2',
    lessonId: 'inst_3_3',
    degreeNumber: 3,
    order: 2,
    type: 'true_false',
    prompt: 'A mestria maçônica é caracterizada pela humildade sincera, pois quem mais sabe mais compreende o quanto ainda tem a aprender.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. A verdadeira sabedoria afasta toda arrogância e aproxima o Mestre da modéstia socrática.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_3_3',
    lessonId: 'inst_3_3',
    degreeNumber: 3,
    order: 3,
    type: 'multiple_choice',
    prompt: 'A liderança do Mestre na Maçonaria é exercida primordialmente por:',
    options: [
      'Poder econômico e imposição autoritária de ordens.',
      'Pelo Exemplo de integridade, dedicação, assiduidade e amor à Verdade.',
      'Ameaças de expulsão da Instituição.',
      'Promessas de cargos políticos profanos.',
    ],
    correctAnswer: '1',
    explanation: 'As palavras ensinam, mas o exemplo arrasta. A autoridade maçônica é estritamente moral.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_3_4',
    lessonId: 'inst_3_3',
    degreeNumber: 3,
    order: 4,
    type: 'true_false',
    prompt: 'Ao ingressar na Câmara do Meio, o Mestre tem direito a descanso perpétuo, desobrigando-se de frequentar os trabalhos e produzir estudos.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '1',
    explanation: 'Falso. No Grau 3, as responsabilidades aumentam exponencialmente; o Mestre é o esteio da Loja.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_3_5',
    lessonId: 'inst_3_3',
    degreeNumber: 3,
    order: 5,
    type: 'multiple_choice',
    prompt: 'Em reuniões administrativas e debates internos, qual deve ser a postura do Mestre Maçom diante de conflitos de opinião?',
    options: [
      'Fomentar facções e polarizações rancorosas.',
      'Pacificador imparcial, buscando pontos de convergência, concórdia e justiça fraterna.',
      'Ficar em silêncio indiferente permitindo a desagregação do grupo.',
      'Ofender publicamente quem defende ideias contrárias.',
    ],
    correctAnswer: '1',
    explanation: 'O Mestre é o pacificador que une o que está disperso e dissipa as tempestades com a sabedoria da concórdia.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_3_6',
    lessonId: 'inst_3_3',
    degreeNumber: 3,
    order: 6,
    type: 'true_false',
    prompt: 'O domínio sobre si mesmo (as próprias emoções, orgulho e impulsos) é a maior de todas as vitórias que coroam a verdadeira Mestria da vida.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. Quem governa a si mesmo é capaz de inspirar e guiar seus semelhantes com justiça.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_3_7',
    lessonId: 'inst_3_3',
    degreeNumber: 3,
    order: 7,
    type: 'multiple_choice',
    prompt: 'Qual atitude um Mestre deve tomar ao constatar que um Aprendiz cometeu um equívoco ritualístico em Loja?',
    options: [
      'Ridicularizá-lo em público diante de todos os presentes.',
      'Instruí-lo reservadamente e com carinho fraternal, explicando os motivos do procedimento correto.',
      'Propor sua suspensão imediata.',
      'Falar mal dele pelas costas em conversas profanas.',
    ],
    correctAnswer: '1',
    explanation: 'A repreensão fraterna deve ser sempre discreta, bondosa e eminentemente pedagógica.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_3_8',
    lessonId: 'inst_3_3',
    degreeNumber: 3,
    order: 8,
    type: 'true_false',
    prompt: 'O Mestre Maçom deve ser um defensor incansável da Liberdade de consciência, da Igualdade de direitos e da Fraternidade universal no mundo profano.',
    options: ['Verdadeiro', 'Falso'],
    correctAnswer: '0',
    explanation: 'Verdadeiro. O lema trino da Maçonaria encontra no Mestre seu guardião ativo e vigilante.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_3_9',
    lessonId: 'inst_3_3',
    degreeNumber: 3,
    order: 9,
    type: 'multiple_choice',
    prompt: 'A plenitude dos direitos do Mestre Maçom confere a ele a capacidade de:',
    options: [
      'Votar, ser votado para cargos diretivos e assumir a responsabilidade direta pelo destino de sua Oficina.',
      'Descumprir as leis civis de seu país de origem.',
      'Faltar sem justificativa aos trabalhos e ainda assim receber honrarias.',
      'Criar dogmas religiosos obrigatórios para os outros.',
    ],
    correctAnswer: '0',
    explanation: 'O Mestre desfruta de plenitude de direitos civis maçônicos (voto e elegibilidade) para gerir com zelo a Instituição.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'q_3_3_10',
    lessonId: 'inst_3_3',
    degreeNumber: 3,
    order: 10,
    type: 'written',
    prompt: 'Sintetize como a vivência do Grau de Mestre Maçom na "Câmara do Meio" prepara o homem para ser um líder ético, compassivo e exemplar em suas atividades profissionais e familiares.',
    options: [],
    correctAnswer: 'Critério de correção: O irmão deve demonstrar que o Mestre alia a firmeza moral à empatia; sabe ouvir antes de julgar; lidera pelo exemplo de dedicação; age como mediador sereno de conflitos; e coloca os valores humanitários acima de vaidades pessoais.',
    explanation: 'Avaliação discursiva corrigida pelo instrutor responsável.',
    points: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Sample demo users for immediate interactive testing of all three roles and degrees
export const DEMO_PROFILES: UserProfile[] = [
  {
    id: 'demo_admin',
    fullName: 'Ir. João da Silva Guimarães',
    masonicName: 'Salomão da Fraternidade',
    email: 'faculdademaconicauniversal@gmail.com',
    phone: '(11) 98765-4321',
    lodge: 'ARLS Luz e Sabedoria nº 33',
    grandLodge: 'Grande oriente Maçonico Universal GOMAU',
    degree: 3,
    cimNumber: 'CIM-102938',
    age: 48,
    role: 'admin',
    status: 'approved',
    temporaryPassword: 'admin123',
    photoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'demo_instructor',
    fullName: 'Ir. Carlos Alberto de Oliveira',
    masonicName: 'Aristóteles do Oriente',
    email: 'instrutor.carlos@faculdademaconica.org',
    phone: '(21) 99887-6655',
    lodge: 'ARLS Estrela do Sul nº 142',
    grandLodge: 'Grande Loja Maçônica de Minas Gerais (GLMEMG)',
    degree: 3,
    cimNumber: 'CIM-245890',
    age: 52,
    role: 'instructor',
    status: 'approved',
    photoURL: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-05T00:00:00Z',
    updatedAt: '2026-01-05T00:00:00Z',
  },
  {
    id: 'demo_brother_aprendiz',
    fullName: 'Ir. Pedro Henrique Santos',
    masonicName: 'Neófito da Aurora',
    email: 'irmao.aprendiz@faculdademaconica.org',
    phone: '(31) 97766-5544',
    lodge: 'ARLS Cavaleiros da Concórdia nº 88',
    grandLodge: 'Grande Loja do Estado de São Paulo (GLESP)',
    degree: 1,
    cimNumber: 'CIM-399120',
    age: 33,
    role: 'brother',
    status: 'approved',
    photoURL: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },
  {
    id: 'demo_brother_companheiro',
    fullName: 'Ir. Marcos Vinícius Lima',
    masonicName: 'Geômetra da Paz',
    email: 'irmao.companheiro@faculdademaconica.org',
    phone: '(41) 98822-3344',
    lodge: 'ARLS Hiram Abiff nº 19',
    grandLodge: 'COMAB - Confederação Maçônica do Brasil',
    degree: 2,
    cimNumber: 'CIM-288410',
    age: 41,
    role: 'brother',
    status: 'approved',
    photoURL: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-12T00:00:00Z',
    updatedAt: '2026-01-12T00:00:00Z',
  },
  {
    id: 'demo_brother_pending',
    fullName: 'Ir. Gabriel Antunes Silva',
    masonicName: 'Buscador da Luz',
    email: 'candidato.gabriel@faculdademaconica.org',
    phone: '(81) 99112-8877',
    lodge: 'ARLS União Fraterna nº 07',
    grandLodge: 'Grande oriente Maçonico Universal GOMAU',
    degree: 1,
    cimNumber: 'CIM-501234',
    age: 28,
    role: 'brother',
    status: 'pending',
    photoURL: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-02-15T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },
];

export const INITIAL_DELIVERED_INSTRUCTIONS: DeliveredInstruction[] = [
  {
    id: 'inst_deliv_1',
    title: 'Os Instrumentos do Aprendiz: O Maço e o Cinzel no Desbaste da Pedra Bruta',
    date: '2026-08-18',
    lodgeName: 'ARLS Luz e Sabedoria nº 33',
    orientCity: 'Oriente de Belo Horizonte - MG',
    grandLodge: 'Grande Oriente Maçônico Universal (GOMAU)',
    instructorName: 'Ir. Janderson Camargos',
    instructorRole: 'Grande Inspetor Geral / Instrutor Docente',
    instructorCim: 'CIM-102938',
    degreeNumber: 1,
    degreeName: 'Grau 01 • Aprendiz Maçom',
    sessionType: 'Sessão Magna de Instrução',
    attendeesCount: 28,
    summaryNotes: 'Aprofundamento simbólico no uso do Maço (vontade ativa e direcionada) e do Cinzel (inteligência e discernimento moral) na purificação das paixões profanas e lapidação da Pedra Bruta.',
    practicalExercises: 'Exercício prático de silêncio meditativo e leitura de Prancha de Arquitetura no Átrio.',
    status: 'concluida',
    registeredById: 'admin_darlan',
    registeredByName: 'S.·. G.·. M.·. Darlan Martins',
    createdAt: '2026-08-18T20:30:00Z',
    updatedAt: '2026-08-18T22:00:00Z',
  },
  {
    id: 'inst_deliv_2',
    title: 'O Painel da Loja de Aprendiz, o Pavimento Mosaico e a Orla Dentada',
    date: '2026-08-11',
    lodgeName: 'ARLS Estrela do Sul nº 142',
    orientCity: 'Oriente de Juiz de Fora - MG',
    grandLodge: 'Grande Loja Maçônica de Minas Gerais (GLMEMG)',
    instructorName: 'Ir. Carlos Alberto de Oliveira',
    instructorRole: '2º Vigilante / Instrutor de Aprendizes',
    instructorCim: 'CIM-245890',
    degreeNumber: 1,
    degreeName: 'Grau 01 • Aprendiz Maçom',
    sessionType: 'Sessão Econômica Ordinária',
    attendeesCount: 22,
    summaryNotes: 'Estudo detalhado do Templo como representação do Cosmo. Análise do Pavimento Mosaico (dualidade humana) e a união fraternal simbolizada pela Corda de 81 Nós.',
    practicalExercises: 'Circulação e orientação ritualística no Templo com os aprendizes recém-iniciados.',
    status: 'concluida',
    registeredById: 'demo_instructor',
    registeredByName: 'Ir. Carlos Alberto de Oliveira',
    createdAt: '2026-08-11T20:00:00Z',
    updatedAt: '2026-08-11T21:45:00Z',
  },
  {
    id: 'inst_deliv_3',
    title: 'A Estrela Flamejante, a Letra G e a Marcha do Companheiro',
    date: '2026-08-04',
    lodgeName: 'ARLS Hiram Abiff nº 19',
    orientCity: 'Oriente de São Paulo - SP',
    grandLodge: 'COMAB - Confederação Maçônica do Brasil',
    instructorName: 'Ir. Darlan Martins',
    instructorRole: 'Soberano Grão-Mestre',
    instructorCim: 'CIM-000001',
    degreeNumber: 2,
    degreeName: 'Grau 02 • Companheiro Maçom',
    sessionType: 'Sessão Magna de Instrução de Companheiros',
    attendeesCount: 34,
    summaryNotes: 'Exposição magistral sobre a transição do trabalho na Pedra Bruta para a Pedra Cúbica de Ponta. O mistério da Letra G (Geometria, Geração, Gênio, Gravitação) e a luz interior emanada pelo pentagrama.',
    practicalExercises: 'Demonstração ritualística da Marcha do Companheiro e esquadrejamento do Templo.',
    status: 'concluida',
    registeredById: 'admin_darlan',
    registeredByName: 'S.·. G.·. M.·. Darlan Martins',
    createdAt: '2026-08-04T19:30:00Z',
    updatedAt: '2026-08-04T22:30:00Z',
  },
  {
    id: 'inst_deliv_4',
    title: 'A Câmara do Meio, a Lenda de Hiram Abiff e o Ramo de Acácia',
    date: '2026-07-28',
    lodgeName: 'ARLS Cavaleiros da Concórdia nº 88',
    orientCity: 'Oriente de Campinas - SP',
    grandLodge: 'Grande Loja do Estado de São Paulo (GLESP)',
    instructorName: 'Ir. Janderson Camargos',
    instructorRole: 'Grande Inspetor Geral / Instrutor Docente',
    instructorCim: 'CIM-102938',
    degreeNumber: 3,
    degreeName: 'Grau 03 • Mestre Maçom',
    sessionType: 'Sessão em Câmara do Meio (Instrução Doutrinária)',
    attendeesCount: 19,
    summaryNotes: 'Estudo hermético da fidelidade inabalável ao dever e a vitória da Verdade sobre a Ignorância, a Hipocrisia e a Ambição. A simbologia da imortalidade através da Acácia florida.',
    practicalExercises: 'Debate filosófico e leitura de Prancha de Arquitetura reservada a Mestres Maçons.',
    status: 'concluida',
    registeredById: 'admin_darlan',
    registeredByName: 'Ir. Janderson Camargos',
    createdAt: '2026-07-28T20:00:00Z',
    updatedAt: '2026-07-28T22:15:00Z',
  },
  {
    id: 'inst_deliv_5',
    title: 'As Três Grandes Luzes e as Três Colunas: Sabedoria, Força e Beleza',
    date: '2026-07-21',
    lodgeName: 'ARLS União Fraterna nº 07',
    orientCity: 'Oriente de Recife - PE',
    grandLodge: 'Grande Oriente Maçônico Universal (GOMAU)',
    instructorName: 'Ir. Roberto Mendes de Carvalho',
    instructorRole: '1º Vigilante / Mestre de Instrução',
    instructorCim: 'CIM-311890',
    degreeNumber: 1,
    degreeName: 'Grau 01 • Aprendiz Maçom',
    sessionType: 'Sessão Econômica de Instrução',
    attendeesCount: 25,
    summaryNotes: 'Estudo das Três Colunas que sustentam o Templo (Salomão, Hiram de Tiro e Hiram Abiff) e das Três Grandes Luzes Emblemas da Ordem: Livro da Lei Sagrada, Esquadro e Compasso.',
    practicalExercises: 'Verificação dos toques, palavras e sinais do primeiro grau com os aprendizes.',
    status: 'concluida',
    registeredById: 'demo_instructor',
    registeredByName: 'Ir. Roberto Mendes de Carvalho',
    createdAt: '2026-07-21T20:00:00Z',
    updatedAt: '2026-07-21T21:40:00Z',
  },
  {
    id: 'inst_deliv_6',
    title: 'As Cinco Viagens Simbólicas e as Sete Artes e Ciências Liberais',
    date: '2026-07-14',
    lodgeName: 'ARLS Luz e Sabedoria nº 33',
    orientCity: 'Oriente de Belo Horizonte - MG',
    grandLodge: 'Grande Oriente Maçônico Universal (GOMAU)',
    instructorName: 'Ir. Alexandre Magno Silveira',
    instructorRole: 'Venerável Mestre',
    instructorCim: 'CIM-154920',
    degreeNumber: 2,
    degreeName: 'Grau 02 • Companheiro Maçom',
    sessionType: 'Sessão Magna de Elevação e Instrução',
    attendeesCount: 31,
    summaryNotes: 'Análise profunda do Trivium (Gramática, Lógica, Retórica) e Quadrivium (Aritmética, Geometria, Música e Astronomia) como caminhos para a elevação intelectual do Companheiro.',
    practicalExercises: 'Apresentação de Prancha por Companheiro recém-elevado com considerações do Orador.',
    status: 'concluida',
    registeredById: 'admin_darlan',
    registeredByName: 'Ir. Alexandre Magno Silveira',
    createdAt: '2026-07-14T19:30:00Z',
    updatedAt: '2026-07-14T22:00:00Z',
  },
  {
    id: 'inst_deliv_7',
    title: 'O Dever de Silêncio e a Modéstia do Aprendiz no Templo e na Sociedade',
    date: '2026-08-29',
    lodgeName: 'ARLS Luz e Sabedoria nº 33',
    orientCity: 'Oriente de Belo Horizonte - MG',
    grandLodge: 'Grande Oriente Maçônico Universal (GOMAU)',
    instructorName: 'Ir. Janderson Camargos',
    instructorRole: 'Grande Inspetor Geral / Instrutor Docente',
    instructorCim: 'CIM-102938',
    degreeNumber: 1,
    degreeName: 'Grau 01 • Aprendiz Maçom',
    sessionType: 'Sessão de Instrução Especial',
    attendeesCount: 26,
    summaryNotes: 'Próxima instrução programada para recepcionar os novos iniciados com aprofundamento na Coluna do Norte.',
    practicalExercises: 'Roda de perguntas entre os Irmãos Vigilantes e Aprendizes.',
    status: 'agendada',
    registeredById: 'admin_darlan',
    registeredByName: 'Ir. Janderson Camargos',
    createdAt: '2026-08-22T10:00:00Z',
    updatedAt: '2026-08-22T10:00:00Z',
  },
];

export const INITIAL_SUPPORT_MATERIALS: SupportMaterial[] = [
  // PDFs / Documentos
  {
    id: 'mat_pdf_1',
    title: 'Manual de Instruções e Ritualística do Aprendiz Maçom (R.E.A.A.)',
    description: 'Guia doutrinário com os passos fundamentais, toques, palavras de passe, postura em Templo, desbaste da Pedra Bruta e exegese dos símbolos do 1º Grau.',
    mediaType: 'pdf',
    degreeNumber: 1,
    degreeName: 'Grau 01 • Aprendiz Maçom',
    category: 'Rituais & Liturgia',
    fileName: 'Manual_Instrucao_Aprendiz_REAA_GOMAU.pdf',
    fileSize: '4.8 MB',
    pagesCount: 48,
    author: 'Grande Inspetor Geral / Comissão de Doutrina',
    uploaderName: 'Ir. Janderson Camargos',
    uploaderRole: 'Grande Inspetor Geral / Instrutor Docente',
    tags: ['aprendiz', 'ritualística', 'pedra bruta', 'manual'],
    downloadsCount: 142,
    viewsCount: 380,
    featured: true,
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'mat_pdf_2',
    title: 'Compêndio de Simbologia Maçônica, Geometria e Artes Liberais',
    description: 'Estudo aprofundado do Trivium e Quadrivium, a Estrela Flamígera, a Letra G, a passagem da régua de 24 polegadas, alavanca e a geometria sagrada do Templo.',
    mediaType: 'pdf',
    degreeNumber: 2,
    degreeName: 'Grau 02 • Companheiro Maçom',
    category: 'Simbologia & Filosofia',
    fileName: 'Compendio_Simbologia_Artes_Liberais_Grau2.pdf',
    fileSize: '6.2 MB',
    pagesCount: 64,
    author: 'Faculdade Maçônica Universal • Corpo Docente',
    uploaderName: 'S.·. G.·. M.·. Darlan Martins',
    uploaderRole: 'Soberano Grão-Mestre / Chanceler',
    tags: ['companheiro', 'trivium', 'quadrivium', 'estrela flamígera', 'geometria'],
    downloadsCount: 98,
    viewsCount: 260,
    featured: true,
    createdAt: '2026-07-05T14:00:00Z',
    updatedAt: '2026-07-05T14:00:00Z',
  },
  {
    id: 'mat_pdf_3',
    title: 'A Lenda de Hiram Abiff e a Filosofia da Câmara do Meio',
    description: 'Peça de arquitetura e análise filosófica sobre a morte e renascimento iniciático, o Ramo de Acácia, a imortalidade moral e o cumprimento do dever do Mestre.',
    mediaType: 'pdf',
    degreeNumber: 3,
    degreeName: 'Grau 03 • Mestre Maçom',
    category: 'História & Tradição',
    fileName: 'Lenda_Hiram_Abiff_Camara_do_Meio_Grau3.pdf',
    fileSize: '5.5 MB',
    pagesCount: 52,
    author: 'Conselho de Mestres Instalados',
    uploaderName: 'Ir. Alexandre Magno Silveira',
    uploaderRole: 'Venerável Mestre',
    tags: ['mestre', 'hiram abiff', 'câmara do meio', 'acácia'],
    downloadsCount: 115,
    viewsCount: 310,
    featured: true,
    createdAt: '2026-07-10T16:00:00Z',
    updatedAt: '2026-07-10T16:00:00Z',
  },
  {
    id: 'mat_pdf_4',
    title: 'Vade-Mécum dos Landmarks Tradicionais e Constituição Maçônica',
    description: 'Coletânea comentada dos 25 Landmarks de Albert Mackey, leis gerais, deveres perante o Grande Arquiteto do Universo e regularidade das Lojas.',
    mediaType: 'pdf',
    degreeNumber: 0,
    degreeName: 'Geral • Todos os Graus',
    category: 'Landmarks & Legislação',
    fileName: 'VadeMecum_Landmarks_Constituicao_Maconica.pdf',
    fileSize: '3.9 MB',
    pagesCount: 36,
    author: 'Grande Oriente Maçônico Universal (GOMAU)',
    uploaderName: 'S.·. G.·. M.·. Darlan Martins',
    uploaderRole: 'Soberano Grão-Mestre / Chanceler',
    tags: ['landmarks', 'legislação', 'mackey', 'regularidade'],
    downloadsCount: 180,
    viewsCount: 450,
    featured: false,
    createdAt: '2026-07-12T11:00:00Z',
    updatedAt: '2026-07-12T11:00:00Z',
  },

  // Vídeos Doutrinários
  {
    id: 'mat_vid_1',
    title: 'Exegese das Três Grandes Colunas: Sabedoria, Força e Beleza',
    description: 'Aula magistral explicativa sobre as ordens arquitetônicas (Jônica, Dórica e Coríntia), sua relação com as Três Luzes de Loja e a sustentação do Templo Interior.',
    mediaType: 'video',
    degreeNumber: 1,
    degreeName: 'Grau 01 • Aprendiz Maçom',
    category: 'Simbologia & Filosofia',
    duration: '24:15',
    externalUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    embedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    author: 'Ir. Janderson Camargos',
    uploaderName: 'Ir. Janderson Camargos',
    uploaderRole: 'Grande Inspetor Geral / Instrutor Docente',
    tags: ['vídeo', 'três colunas', 'aprendiz', 'sabedoria', 'força', 'beleza'],
    downloadsCount: 65,
    viewsCount: 520,
    featured: true,
    createdAt: '2026-07-15T18:00:00Z',
    updatedAt: '2026-07-15T18:00:00Z',
  },
  {
    id: 'mat_vid_2',
    title: 'As Cinco Viagens do Companheiro e a Glorificação do Trabalho',
    description: 'Vídeo instrutivo detalhando cada uma das cinco etapas de transição do Grau 2, o uso das ferramentas operativas e a conquista do conhecimento humano.',
    mediaType: 'video',
    degreeNumber: 2,
    degreeName: 'Grau 02 • Companheiro Maçom',
    category: 'Rituais & Liturgia',
    duration: '31:40',
    externalUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    embedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    author: 'Faculdade Maçônica Universal',
    uploaderName: 'Ir. Roberto Mendes de Carvalho',
    uploaderRole: 'Instrutor Docente / 1º Vigilante',
    tags: ['vídeo', 'companheiro', 'viagens', 'ferramentas'],
    downloadsCount: 42,
    viewsCount: 390,
    featured: true,
    createdAt: '2026-07-18T19:30:00Z',
    updatedAt: '2026-07-18T19:30:00Z',
  },
  {
    id: 'mat_vid_3',
    title: 'Abertura e Fechamento Ritualístico dos Trabalhos em Templo',
    description: 'Demonstração detalhada das falas, acendimento das luzes, verificação da cobertura do templo e circulação sagrada na Loja Maçônica.',
    mediaType: 'video',
    degreeNumber: 0,
    degreeName: 'Geral • Todos os Graus',
    category: 'Rituais & Liturgia',
    duration: '19:50',
    externalUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    embedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    author: 'Grande Oriente Maçônico Universal (GOMAU)',
    uploaderName: 'S.·. G.·. M.·. Darlan Martins',
    uploaderRole: 'Soberano Grão-Mestre / Chanceler',
    tags: ['vídeo', 'ritual', 'abertura de loja', 'tronco de beneficência'],
    downloadsCount: 88,
    viewsCount: 610,
    featured: false,
    createdAt: '2026-07-20T20:00:00Z',
    updatedAt: '2026-07-20T20:00:00Z',
  },

  // Áudios / Podcasts / Harmonia
  {
    id: 'mat_aud_1',
    title: 'Podcast Doutrinário: O Desbaste da Pedra Bruta e o Silêncio',
    description: 'Áudio com reflexões profundas sobre a autodisciplina diária do iniciado, a contenção das paixões profanas e o cultivo do amor fraternal.',
    mediaType: 'audio',
    degreeNumber: 1,
    degreeName: 'Grau 01 • Aprendiz Maçom',
    category: 'Simbologia & Filosofia',
    duration: '16:22',
    fileSize: '15.4 MB',
    author: 'Ir. Janderson Camargos',
    uploaderName: 'Ir. Janderson Camargos',
    uploaderRole: 'Grande Inspetor Geral / Instrutor Docente',
    tags: ['áudio', 'podcast', 'silêncio', 'pedra bruta', 'iniciação'],
    downloadsCount: 94,
    viewsCount: 430,
    featured: true,
    createdAt: '2026-07-22T09:00:00Z',
    updatedAt: '2026-07-22T09:00:00Z',
  },
  {
    id: 'mat_aud_2',
    title: 'Harmonia Maçônica: Peças e Hinos Solenes para Sessões do R.E.A.A.',
    description: 'Compilação de músicas instrumentais solenes (órgão clássico, trombetas e corais) para entrada do cortejo, acendimento das Três Luzes e cadeia de união.',
    mediaType: 'audio',
    degreeNumber: 0,
    degreeName: 'Geral • Todos os Graus',
    category: 'Música Harmônica',
    duration: '45:10',
    fileSize: '42.1 MB',
    author: 'Comissão de Harmonia da Faculdade Maçônica',
    uploaderName: 'S.·. G.·. M.·. Darlan Martins',
    uploaderRole: 'Soberano Grão-Mestre / Chanceler',
    tags: ['harmonia', 'música', 'hino maçônico', 'cadeia de união'],
    downloadsCount: 156,
    viewsCount: 780,
    featured: true,
    createdAt: '2026-07-25T15:00:00Z',
    updatedAt: '2026-07-25T15:00:00Z',
  },
  {
    id: 'mat_aud_3',
    title: 'Áudio-Instrução: A Marcha do Mestre e os Cinco Pontos da Perfeição',
    description: 'Estudo em áudio narrado sobre a ressurreição moral do Mestre, a solidariedade incondicional entre Irmãos e os laços indissolúveis da Fraternidade.',
    mediaType: 'audio',
    degreeNumber: 3,
    degreeName: 'Grau 03 • Mestre Maçom',
    category: 'História & Tradição',
    duration: '21:05',
    fileSize: '19.8 MB',
    author: 'Ir. Alexandre Magno Silveira',
    uploaderName: 'Ir. Alexandre Magno Silveira',
    uploaderRole: 'Venerável Mestre',
    tags: ['áudio', 'mestre', 'cinco pontos', 'perfeição'],
    downloadsCount: 82,
    viewsCount: 340,
    featured: false,
    createdAt: '2026-07-28T17:00:00Z',
    updatedAt: '2026-07-28T17:00:00Z',
  },
];
